2019-11-23 11:32:38,514 - ERROR - flask_server.py - zip_server - 46 - 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/root/work/data_handle/flask_server.py", line 37, in zip_server
    file = request.files['img']  # 获取上传的文件
  File "/usr/local/lib/python3.7/site-packages/werkzeug/datastructures.py", line 443, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2019-11-23 11:32:54,575 - ERROR - flask_server.py - zip_server - 46 - [Errno 2] No such file or directory: 'temp/temp.png20190930124444.png'
Traceback (most recent call last):
  File "/root/work/data_handle/flask_server.py", line 41, in zip_server
    result = image_zip(filename)
  File "/root/work/data_handle/src/zip_png.py", line 18, in image_zip
    os.remove(Config.new_image_path + file_name)
FileNotFoundError: [Errno 2] No such file or directory: 'temp/temp.png20190930124444.png'
